title: "Reihaneh Farzinnia"
author: "Reihaneh Farzinnia"
description: "PhD student at The University of Manchester"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true              # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "about.md", sidebaricon: home}
  - {file: "CV.md", sidebaricon: file-alt}
  - {file: "publications.md", sidebaricon: book}
  - {file: "projects.md", sidebaricon: project-diagram}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:reihaneh.farzinnia@postgrad.manchester.ac.uk"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=gkGxtgIAAAAJ&hl=en"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0003-4480-5655"}
  - {title: Bluesky, icon: feather, url: "https://bsky.app/profile/reihaneh-farzinnia.bsky.social"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/reihaneh-farzinnia"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
